-- Addon-level preset definitions.
-- You can add more presets here and ship them with the addon.
-- Each preset supports partial or full cvar lists.
return {
	defaultPresetName = "Default",
	presets = {
		["Comfort"] = {
			vrmod_brushclimb_launch_mult = "1.10",
			vrmod_brushclimb_launch_max = "500",
			vrmod_brushclimb_camera_collision = "1",
			vrmod_brushclimb_assist_enable = "1",
			vrmod_brushclimb_assist_strength = "90",
			vrmod_wallrun_look_max_dot = "0.35",
			vrmod_slide_head_height = "44",
		},
		["Arcade"] = {
			vrmod_brushclimb_launch_mult = "1.65",
			vrmod_brushclimb_launch_max = "900",
			vrmod_brushclimb_assist_enable = "1",
			vrmod_brushclimb_assist_strength = "120",
			vrmod_wallrun_hand_range = "24",
			vrmod_wallrun_look_max_dot = "0.60",
			vrmod_slide_enable = "1",
			vrmod_slide_head_height = "36",
		},
		["STRIDE"] = {
			vrmod_brushclimb_grab_distance = "22",
			vrmod_brushclimb_doorbash_enable = "1",
			vrmod_brushclimb_allow_floors = "1",
			vrmod_brushclimb_allow_ceilings = "0",
			vrmod_brushclimb_palm_offset_forward_right = "3.30",
			vrmod_brushclimb_launch_min = "120",
			vrmod_brushclimb_launch_max = "443",
			vrmod_brushclimb_allow_doors = "0",
			vrmod_slide_enable = "1",
			vrmod_brushclimb_allow_walls = "0",
			vrmod_wallrun_cooldown = "0.5",
			vrmod_wallrun_look_max_dot = "0.45",
			vrmod_brushclimb_armswing_jump_cooldown = "0.180000",
			vrmod_slide_sounds = "1",
			vrmod_brushclimb_debug_text = "1",
			vrmod_brushclimb_enable = "1",
			vrmod_wallrun_hand_range = "48",
			vrmod_brushclimb_armswing_jump_speed = "110",
			vrmod_brushclimb_bind_mode = "1",
			vrmod_brushclimb_armswing_jump_enable = "1",
			vrmod_brushclimb_doorbash_cooldown = "0.140000",
			vrmod_brushclimb_sounds = "1",
			vrmod_brushclimb_allow_pushable = "0",
			vrmod_brushclimb_allow_ladders = "1",
			vrmod_brushclimb_doorbash_range = "22",
			vrmod_wallrun_sound_volume = "0.75",
			vrmod_brushclimb_doorbash_speed = "200",
			vrmod_slide_sound_volume = "0.75",
			vrmod_brushclimb_assist_strength = "165",
			vrmod_brushclimb_assist_enable = "1",
			vrmod_brushclimb_palm_offset_forward = "3.30",
			vrmod_slide_head_height = "40",
			vrmod_brushclimb_allow_toggleable = "0",
			vrmod_brushclimb_launch_mult = "1.02",
			vrmod_brushclimb_wall_push_dist = "1.5",
			vrmod_brushclimb_sound_volume = "0.80",
			vrmod_brushclimb_camera_collision = "1",
			vrmod_wallrun_air_regen = "2.0",
			vrmod_brushclimb_debug = "0",
			vrmod_wallrun_bind_mode = "1",
			vrmod_wallrun_sound_interval = "0.18",
			vrmod_brushclimb_palm_offset_right = "-2.32",
			vrmod_brushclimb_allow_ledges = "1",
			vrmod_brushclimb_palm_offset_up_right = "0.05",
			vrmod_brushclimb_palm_offset_up = "-0.05",
			vrmod_brushclimb_palm_offset_right_right = "2.32",
			vrmod_brushclimb_hand_inset = "0.0",
			vrmod_wallrun_sounds = "1",
		},
	},
}